#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
search_dir=${SCRIPT_DIR}/../src/

i686-elf-g++ -m32 -ffreestanding -I${SCRIPT_DIR}/../include -Wno-write-strings -std=c++20 -mno-red-zone -nostdlib -fconcepts-ts -T ${SCRIPT_DIR}/link.ld "$search_dir"/*.o $@
