CPP = i686-elf-g++
CPP_FLAGS = -m32 -ffreestanding -I../../../include -Wno-write-strings -std=c++20 -mno-red-zone -nostdlib -fconcepts-ts -T ../../link.ld
FOLDER = base

EXTERNAL := $(wildcard ../../../src/*.o)

LINKER = i686-elf-ld
